<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ', software solutions' => ', soluciones con software',
    'Call us at {app}' => 'Llámenos',
    'Contact' => 'Contacto',
    'Contact Us!' => '¡Contáctenos!',
    'Contact with {app}' => 'Conctactar con {app}',
    'Daxslab{slogan}' => 'Daxslab{slogan}',
    'I\'m interested in {service}' => 'Estoy interesando en {servicio}',
    'If you are interested in develop a new project or update and existing one, don\'t hesitate in contacting us.' => 'Si está interesado en desarrollar un nuevo proyecto o actualizar uno existente, no dude en contactarnos',
    'Image on project {name} developed by Daxslab' => 'Imagen del proyecto {name} desarrollado por Daxslab',
    'Our Stack' => 'Nuestras tecnologías',
    'Projects we have completed' => 'Proyectos completados',
    'Read more...' => 'Leer más...',
    'Request service' => 'Solicitar Servicio',
    'Send a message' => 'Enviar Mensaje',
    'Tech' => 'Tecnologías',
    'URL' => '',
];
